<?php

namespace App\Admin\Repositories;

use App\Models\User as Model;
use Dcat\Admin\Form;
use Dcat\Admin\Grid;
use Dcat\Admin\Repositories\EloquentRepository;
use Dcat\Admin\Show;
use Illuminate\Support\Facades\Log;

class User extends EloquentRepository
{
    /**
     * Model.
     *
     * @var string
     */
    protected $eloquentClass = Model::class;


    /**
     * 用于数据表单修改记录，可以返回 int、string 或 bool 类型值。
     *
     * @param Form $form
     * @return bool|null
     */
    public function update(Form $form)
    {
        // 获取待编辑的数据
        $attributes = $form->updates();

        // 修改 传递过来的值
        $form->updates(['password'=>bcrypt(trim(htmlspecialchars($attributes['password'])))]);

//        $attributes['password'] = bcrypt(trim(htmlspecialchars($attributes['password'])));
        return parent::update($form); // TODO: Change the autogenerated stub
    }

    public function store(Form $form)
    {
        $attributes = $form->updates();
        $data = [
            'email_verified_at' => time(),
            'password' => bcrypt(trim(htmlspecialchars($attributes['password'])))
        ];
        $form->updates($data);
        return parent::store($form); // TODO: Change the autogenerated stub
    }
}
